services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your-db-username
      POSTGRES_PASSWORD: your-db-password
      POSTGRES_DB: your-db-name
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
